### PR TITLE
Min/max a.k.a {x,y}

### PR DESCRIPTION
**Pull request by danielnaber**
I needed a min/max expression, so I wrote one. I'm not sure if my approach is the best one, but it seems to work for me. I know the use of short as a data type is unusual for Java, you might want to re-consider that. Sorry for being too lazy to write a Scala test case.

### CODE REVIEW

**Comment by schmmd** [comment]
Very cool!  Thank you for submitting a test case (who cares about the language).

**Comment by schmmd** [comment]
Do you mind reverting to ints (I understand the memory problem but I'd rather not use `short`)?  Could you add an entry to the README about this syntax?  Then I'm ready to merge.  Awesome change.

**Comment by danielnaber** [comment]
I have reverted that change now and updated the README.

**Comment by danielnaber** [comment]
Anything more I can do to get this merged?

**Comment by rbart** [comment]
Michael's been out on vacation, but the change looks good to me, and it looks like you took care of the issues he brought up. I'll go ahead and merge it. Do you want a new release?

**Comment by danielnaber** [comment]
Thanks for merging. A release is currently not necessary.

**Comment by schmmd** [comment]
Thanks Rob!

**Pull request merged**
